[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set DATABASE_URL
# SHADOW_DATABASE_URL should be set to the same value as DATABASE_URL for Railway
SHADOW_DATABASE_URL = "${{DATABASE_URL}}"
